name: Build and Upload Asset
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install build-essential
      - name: Compile main.c
        run: gcc main.c -o main
      - name: Run and check main
        run: echo "7\n" | ./main
      - name: Upload main as asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./main
          asset_name: main
          asset_content_type: application/octet-stream
