name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Compile main.c
      run: gcc -o main main.c
      working-directory: ${{ github.workspace }}

    - name: Run Expect script
      run: echo "7\n" | ./main
      working-directory: ${{ github.workspace }}

    - name: Create Release
      id: create_release
      run: |
        response=$(curl -X POST -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"tag_name": "v1.0", "target_commitish": "main", "name": "Release v1.0", "draft": false, "prerelease": false}' \
          "https://api.github.com/repos/${{ github.repository }}/releases")
        release_id=$(echo "$response" | jq -r '.id')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      run: |
        upload_url="https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.release_id }}/assets?name=main"
        
        curl -X POST -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @main "$upload_url"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
