name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install
    
    - name: Make C
      run: make
      
    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"
      
    - name: Get previous release tag
      id: prev_release
      run: echo "::set-output name=prev_tag::$(git describe --tags --abbrev=0)"
      
    - name: Get commit messages since previous release
      id: commit_messages
      run: |
        git log --pretty=format:"%s" ${{ steps.prev_release.outputs.prev_tag }}..HEAD > commit_messages.txt
        echo "::set-output name=messages::$(cat commit_messages.txt)"
      
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./
        tag_name: v${{ steps.timestamp.outputs.timestamp }}
        release_name: Release ${{ steps.timestamp.outputs.timestamp }}
        draft: false
        prerelease: false
        body: |
          Changes from ${{ steps.prev_release.outputs.prev_tag }} to v${{ steps.timestamp.outputs.timestamp }}:
          
          ${{ steps.commit_messages.outputs.messages }}
